INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('мука', 21400, 'гр', 3660);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('яйца', 1152, 'шт', 30);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('молоко', 9125, 'мл', 32);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('мед', 5520, 'гр', 365);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('какао', 2507, 'гр', 31);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('сливочное масло', -16170, 'гр', 93);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('сахар', -20920, 'гр', 2920);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('желатин', 808, 'гр', 730);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('сгущеное молоко', -2690, 'гр', 365);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('сметана', -9980, 'гр', 10);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('ванильный сахар', 734, 'гр', 730);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('сахарная пудра', -2659, 'гр', 730);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('лимонный сок', 755, 'мл', 122);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('сода', 959, 'гр', 550);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('соль', 565, 'гр', 365);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('коньяк', -671, 'мл', 90);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('абрикосовый джем', 200, 'гр', 365);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('горький шоколад', 320, 'гр', 365);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('маскарпоне', -5350, 'гр', 90);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('кофе', 1523, 'гр', 365);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('савоярди', -450, 'гр', 180);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('сливочный сыр', -12600, 'гр', 90);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('крахмал', 520, 'гр', 730);
INSERT INTO Confect.Store (ingredient, quantity, unit, shelfLife) VALUES ('сливки', 1000, 'мл', 31);